# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---

ingress:
  ingressClassName: "nginx"
  tls:
    secretName: "custom-tls-secret"

postgresql:
  connection:
    host: "postgres"
    port: "5432"
  auth:
    username: "stub-values-username"
    database: "postgres"
    password: "stub-values-password"

keycloak:
  auth:
    username: "admin"
    existingSecret:
      name: "custom-keycloak-credentials"
      keyMapping:
        adminPassword: "admin_password"

...
