{{/*
SPDX-FileCopyrightText: 2023 Univention GmbH
SPDX-License-Identifier: AGPL-3.0-only
*/}}
---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: "Deployment"
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" . ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  strategy: {{ include "common.tplvalues.render" (dict "value" .Values.updateStrategy "context" .) | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" .) | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- if or .Values.imagePullSecrets .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: "{{ . }}"
        {{- end }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: "keycloak"
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ coalesce .Values.image.registry .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          args:
            - "start"
          {{- range .Values.extraStartupArgs }}
            - {{ . | quote }}
          {{- end }}
          {{- with .Values.config.features.enabled }}
            - "--features={{ join "," . }}"
          {{- end }}
          {{- with .Values.config.features.disabled }}
            - "--features-disabled={{ join "," . }}"
          {{- end }}
          {{- if .Values.config.enableMetrics }}
            - "--metrics-enabled=true"
          {{- end }}
          env:
            - name: "KEYCLOAK_ADMIN"
              value: {{ .Values.config.admin.username | quote }}
            {{- with .Values.config.admin }}
            - name: "KEYCLOAK_ADMIN_PASSWORD"
              valueFrom:
                secretKeyRef:
                  {{- if .existingSecret.name }}
                  name: {{ .existingSecret.name | quote }}
                  key: {{ .existingSecret.key | quote }}
                  {{- else }}
                  name: "{{ include "common.names.fullname" $ }}"
                  key: "adminPassword"
                  {{- end }}
            {{- end }}
            - name: "KC_HOSTNAME"
              value: {{ .Values.config.hostname | default (printf "%s.%s" .Values.global.hosts.keycloak .Values.global.domain) | quote }}
            - name: "KC_PROXY"
              value: {{ .Values.config.proxy | quote }}
            - name: "KC_DB"
              value: {{ .Values.config.database.type | quote }}
            - name: "KC_DB_URL_DATABASE"
              value: {{ .Values.config.database.name | quote }}
            - name: "KC_DB_URL_HOST"
              value: {{ .Values.config.database.host | quote }}
            - name: "KC_DB_URL_PORT"
              value: {{ .Values.config.database.port | quote }}
            - name: "KC_DB_URL_PROPERTIES"
              value: {{ .Values.config.database.properties | quote }}
            - name: "KC_DB_USERNAME"
              value: {{ .Values.config.database.username | quote }}
            - name: "UNIVENTION_THEME"
              value: {{ .Values.theme.univentionTheme | quote }}
            - name: "UNIVENTION_CUSTOM_THEME"
              value: {{ .Values.theme.univentionCustomTheme | quote }}
            - name: "UNIVENTION_FAVICON"
              value: {{ .Values.theme.favIcon | quote }}
            {{- with .Values.config.database }}
            - name: "KC_DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  {{- if .existingSecret.name }}
                  name: {{ .existingSecret.name | quote }}
                  key: {{ .existingSecret.key | quote }}
                  {{- else }}
                  name: "{{ include "common.names.fullname" $ }}"
                  key: "databasePassword"
                  {{- end }}
            {{- end }}
          {{- with .Values.extraEnvVars }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          ports:
            {{- range $key, $value := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: "/realms/master"
              port: {{ .Values.service.ports.http.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          readinessProbe:
            httpGet:
              path: "/realms/master"
              port: {{ .Values.service.ports.http.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          startupProbe:
            httpGet:
              path: "/realms/master"
              port: {{ .Values.service.ports.http.containerPort }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
          {{- if .Values.resources }}
          resources: {{- include "common.tplvalues.render" (dict "value" .Values.resources "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.lifecycleHooks "context" .) | nindent 12 }}
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts: {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" .) | nindent 12 }}
          {{- end }}
      {{- if .Values.extraVolumes }}
      volumes: {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes  "context" .) | nindent 8 }}
      {{- end }}
...
